input {
    file {
        path => "/usr/share/logstash/ingest-data/custom-logs/*"
        start_position => "beginning"
        sincedb_path => "/dev/null"
    }
}

filter {
    grok {
        match => {
            "message" => [
                '%{TIMESTAMP_ISO8601:time} %{LOGLEVEL:logLevel} %{GREEDYDATA:logMessage}',
                '%{IP:clientIP} %{WORD:httpMethod} %{URIPATH:url}'
            ]
        }
    }
}

output {
    elasticsearch {
        hosts => "${ES_HOSTS}"
        user => "${LOGSTASH_USER}"
        password => "${LOGSTASH_PASSWORD}"
        ssl_enabled => true
        ssl_certificate_authorities => "${SSL_CERTIFICATE_AUTHORITIES}"
        index => "logstash-custom_logs"
    }
    stdout {}
}
